name: Build & Release

on:
  push: 
    # branches: ["*"]
    paths: 
      - src/**
      - .github/workflows/build.yml 
  workflow_dispatch: 
    inputs:
      release_version:
        description: 'Version number for the release'
        required: true 
        default: '1.0.0'
      publish_release:
        description: 'Publish the release? (true/false)'
        required: true
        default: 'false'

env:
  PROJECT_PATH: src/VIP-Plugin.csproj
  PROJECT_NAME: VIP-Plugin
  OUTPUT_PATH: ./VIP-Plugin

jobs:
  Build: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.204
      - name: Restore
        run: "dotnet restore ${{ env.PROJECT_PATH }}"
      - name: Build 
        run: dotnet publish ${{ env.PROJECT_PATH }} -c ${{ env.PROJECT_NAME }} -o ${{ env.OUTPUT_PATH }}
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PROJECT_NAME }}
          path: ${{ env.OUTPUT_PATH }}

  Publish: 
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.publish_release == 'true'
    permissions: write-all
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: Download Build Artifacts 
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.PROJECT_NAME }}
          path: ${{ env.OUTPUT_PATH }}
      - name: Zip
        uses: thedoctor0/zip-release@0.7.6
        with:
          type: zip
          filename: "${{ env.PROJECT_NAME }}-v${{ github.event.inputs.release_version }}.zip" 
          path:  ${{ env.PROJECT_NAME }}
      - name: Publish 
        uses: ncipollo/release-action@v1.14.0
        with:
          artifacts: "${{ env.PROJECT_NAME }}-v${{ github.event.inputs.release_version }}.zip"
          name: "v${{ github.event.inputs.release_version }}" 
          tag: "v${{ github.event.inputs.release_version }}" 
          body: 
