name: Build & Release

on:
  push: 
    # branches: ["*"]
    paths: 
      - src/**
      - .github/workflows/pr_build_check.yml 

env:
  PROJECT_PATH: src/VIP-Plugin.csproj
  PROJECT_NAME: VIP-Plugin
  OUTPUT_PATH: ./VIP-Plugin

jobs:
  Build: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore
        run: "dotnet restore ${{ env.PROJECT_PATH }}"
      - name: Build 
        run: dotnet publish ${{ env.PROJECT_PATH }} -c ${{ env.PROJECT_NAME }} -o ${{ env.OUTPUT_PATH }}
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PROJECT_NAME }}
          path: ${{ env.OUTPUT_PATH }}
